-- DATA DEFINITION LANGUAGE (DDL)
-- 02.04.2018
-- Atividade de Banco de Dados (Fatece)

CREATE TABLE IF NOT EXISTS REGIONS (
     REGION_ID SMALLINT NOT NULL, 
     REGION_NAME VARCHAR(25),
     CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID) 
 );

CREATE TABLE IF NOT EXISTS COUNTRIES ( 
     COUNTRY_ID CHAR(2)  NOT NULL, 
     COUNTRY_NAME VARCHAR(40), 
     REGION_ID SMALLINT,
     CONSTRAINT COUNTRY_ID_PK PRIMARY KEY (COUNTRY_ID)     
);

CREATE TABLE IF NOT EXISTS JOBS ( 
     JOB_ID VARCHAR (10) NOT NULL, 
     JOB_TITLE VARCHAR (35) NOT NULL, 
     MIN_SALARY DOUBLE PRECISION CHECK (MIN_SALARY > 0.0), 
     MAX_SALARY DOUBLE PRECISION,
     CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID)
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
     LOCATION_ID SMALLINT NOT NULL, 
     STREET_ADDRESS VARCHAR (40), 
     POSTAL_CODE VARCHAR (15), 
     CITY VARCHAR (30) NOT NULL, 
     STATE_PROVINCE VARCHAR (25), 
     COUNTRY_ID CHAR(2),
     CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID),
     CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID)
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS ( 
     DEPARTMENT_ID SMALLINT  NOT NULL, 
     DEPARTMENT_NAME VARCHAR(30)  NOT NULL, 
     MANAGER_ID INTEGER, 
     LOCATION_ID SMALLINT,
     CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID),
     CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID)
 );

CREATE TABLE IF NOT EXISTS EMPLOYEES (
     EMPLOYEE_ID INTEGER NOT NULL, 
     FIRST_NAME VARCHAR(20) NOT NULL, 
     LAST_NAME VARCHAR(25) NOT NULL, 
     EMAIL VARCHAR(25)  NOT NULL, 
     PHONE_NUMBER VARCHAR(20), 
     HIRE_DATE DATE NOT NULL, 
     JOB_ID VARCHAR(10) NOT NULL, 
     SALARY DECIMAL(8,2), 
     COMMISSION_PCT DECIMAL(3,2), 
     MANAGER_ID SMALLINT, 
     DEPARTMENT_ID SMALLINT,
     CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_ID),
     CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
 );

CREATE TABLE IF NOT EXISTS JOB_HISTORY (
    EMPLOYEE_ID INTEGER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    JOB_ID CHAR(10) NOT NULL,
    DEPARTMENT_ID SMALLINT,
    CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_ID,START_DATE)
);